### ISSUE TITLE
Chat UI issue,  duplication / multiplication of messages in UI

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/beehive-desktop#28]
When sending a chat message   sometimes  the message will appear in the chat more then once,

this has been verified on the recipient end as well.

![image](https://user-images.githubusercontent.com/8147049/113653852-f2c50580-96d9-11eb-8eb5-1c6760087ce7.png)

after restarting wallet  it no longer appears.

![image](https://user-images.githubusercontent.com/8147049/113653974-2dc73900-96da-11eb-9715-198dabf41272.png)

**Comment by hockleyj** [comment]
it also appears to  resolve if  going to another chat  and then  going back...  so  not just a restart resolves issue

**Comment by brunohenz** [comment]
This issue is fixed in new version 1.0.7
