### ISSUE TITLE
App esta dando tela preta.

### ISSUE THREAD

**Issue by JoaoGabrielCorrea** [SmartCash/beehive-desktop#41]
Ao navegar entre abar de receive pra transaction app fica em tela preta e mosta a seguinte mensagem em pop-up.

×
TypeError: Cannot read property 'toLocaleString' of undefined
(anonymous function)
C:/Users/User/smarthub_local/src/presentation/pages/transactions/Transactions.js:67
  64 | </div>
  65 | <div>
  66 |     <p className="label">Amount</p>
> 67 |     <p className="value">
     | ^  68 |         {tx.amount
  69 |             .toLocaleString('en-US', {
  70 |                 style: 'currency',
View compiled
Transactions
C:/Users/User/smarthub_local/src/presentation/pages/transactions/Transactions.js:47
  44 | )}
  45 | {error && <p className="error">{error}</p>}
  46 | {!error && history && (
> 47 |     <Scrollbars renderThumbVertical={(props) => <div {...props} className="thumb-vertical" />}>
     | ^  48 |         {history?.map((tx, index) => {
  49 |             tx.isLocked = isLockedTransaction(tx, walletCurrent) ? 'Yes' : 'No';
  50 |             tx.message = getOpReturnMessage(tx);
View compiled
▶ 17 stack frames were collapsed.
(anonymous function)
C:/Users/User/smarthub_local/src/presentation/pages/transactions/Transactions.js:23
  20 | setLoading(true);
  21 | setError(null);
  22 | setHistory([]);
> 23 | await getTransactionHistory(walletCurrent)
     | ^  24 |     .then((data) => setHistory(data))
  25 |     .catch(() => setError('There is no transactions for this wallet'))
  26 |     .finally(() => setLoading(false));
View compiled
async _getTransactionHistory
C:/Users/User/smarthub_local/src/presentation/pages/transactions/Transactions.js:23
  20 | setLoading(true);
  21 | setError(null);
  22 | setHistory([]);
> 23 | await getTransactionHistory(walletCurrent)
     | ^  24 |     .then((data) => setHistory(data))
  25 |     .catch(() => setError('There is no transactions for this wallet'))
  26 |     .finally(() => setLoading(false));
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by brunohenz** [comment]
Essa issue foi corrigida na versão 1.0.6, o erro ocorria quando a wallet não possuia nenhuma transação.
