### ISSUE TITLE
TAB Chat

### ISSUE THREAD

**Issue by JoaoGabrielCorrea** [SmartCash/beehive-desktop#48]
Error sending message in chat tab

"One error happened. Try again in a moment."

**Comment by hockleyj** [comment]
Confirming this issue,  on a new wallet install with new wallet..  on first use of chat i get the same error

![image](https://user-images.githubusercontent.com/8147049/117093375-1ac08b00-ada4-11eb-86d0-0f9adc702bbe.png)
