### ISSUE TITLE
Black Screen -  on Windows compiled version likely SAPI connection related

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/beehive-desktop#50]
Installing precompiled  windows version...   in testing,  if an internet disruption  happens  upstream,  it appears to cause a black screen on the client app...

i have tested turning on and off  VPN to see if this is client side,  but  it does not appear to trigger the issue...  so it appears that the  SAPI connection at the server end  might be behind the black screen issue...

https://contattafiles.s3.us-west-1.amazonaws.com/tnt19836/MTy5WfCNyljGwka/Pasted%20Image%3A%20May%205%2C%202021%20-%2012%3A51%3A09pm

**Comment by hockleyj** [comment]
![image](https://user-images.githubusercontent.com/8147049/117093791-53ad2f80-ada5-11eb-9993-176d768f6e4e.png)

**Comment by brunohenz** [comment]
This issue was fixed in new versions....
