### ISSUE TITLE
UI issue with  padding / spacing of  addresses and copy button causing wrap under

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/beehive-desktop#51]
Using a new install with a new wallet,  the generated addresses  can in some cases cause the copy button to be wrapped under the address...  this appears due to the address length being longer then what is provided...
This was on a maximised 4k screen  and on a resize it didnt not change this behavior...

![image](https://user-images.githubusercontent.com/8147049/117093264-ccab8780-ada3-11eb-9999-36da70179a2c.png)

**Comment by brunohenz** [comment]
This issue was fixed in v1.0.8
