### ISSUE TITLE
Chat invites on 1.0.4  not appearing to work

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/beehive-desktop#52]
On a new install  of V.1.0.4  on windows 10  pre-compiled version.   after adding funds to new wallet.   then going to the chat window,  sending an  invite to  another address within your  list of addresses,  does not appear to be received..   

below is images showing the addresses  and the before and after invite view...    i have tested sending an invite from both addresses to each other  and the result is the same...

![image](https://user-images.githubusercontent.com/8147049/117093594-b94cec00-ada4-11eb-944f-66879e521fd2.png)

![image](https://user-images.githubusercontent.com/8147049/117093611-c7027180-ada4-11eb-8a67-70f3c3785e30.png)

**Comment by brunohenz** [comment]
This issue was fixed in 1.0.7!
