### ISSUE TITLE
Receive QR code  "download"  and "Copy"  function needs text to be active link as well

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/beehive-desktop#53]
Not really a bug but a better implementation of the intended function.  please make the text next to the buttons trigger the same function as the buttons...  the  button and text should both be clickable for the function....

![image](https://user-images.githubusercontent.com/8147049/117094040-0bdad800-ada6-11eb-8409-9e1c64885f0b.png)

**Comment by brunohenz** [comment]
Done!
