### ISSUE TITLE
Chat window: Refresh issue

### ISSUE THREAD

**Issue by ArcherBullseye** [SmartCash/beehive-desktop#65]
When you use the 'refresh' button it should take you to the bottom of the current chat.  Currently it refreshes then takes you to top, and you then need to scroll down.

**Comment by ArcherBullseye** [comment]
Don't know if this will help -
https://stackoverflow.com/questions/17642872/refresh-page-and-keep-scroll-position

**Comment by brunohenz** [comment]
Done!
